name: build-and-deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./app
          push: true
          tags: |
            ${{ secrets.APP_IMAGE }}:latest
            ${{ secrets.APP_IMAGE }}:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.SSH_HOST }}
      USER: ${{ secrets.SSH_USER }}
      IMAGE: ${{ secrets.APP_IMAGE }}
    steps:
      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts

      - name: Deploy on remote server
        run: |
          ssh -i ~/.ssh/id_ed25519 ${USER}@${HOST} << EOF
            set -e
            docker pull ${IMAGE}:latest
            docker rm -f mpay-demo || true
            docker run -d --name mpay-demo --restart unless-stopped \
              -p 80:8000 ${IMAGE}:latest
          EOF

